import { Restaurant } from './restaurant';

export const RESTAURANTS : Restaurant[] = [
   /* {
        code : "1",
        adresse : "Bizerte",    
        email : "restaurant1@gmail.com",
        enabled : true,
        name : "restaurant1",
        image_code : "1",
    },
    {
        code : "2",
        adresse : "Bizerte",    
        email : "restaurant2@gmail.com",
        enabled : true,
        name : "restaurant2",
        image_code : "2",
    },
    {
        code : "3",
        adresse : "Bizerte",    
        email : "restaurant3@gmail.com",
        enabled : true,
        name : "restaurant3",
        image_code : "3",
    },
    {
        code : "4",
        adresse : "Bizerte",    
        email : "restaurant4@gmail.com",
        enabled : true,
        name : "restaurant4",
        image_code : "4",
    },
    {
        code : "5",
        adresse : "Bizerte",    
        email : "restaurant5@gmail.com",
        enabled : true,
        name : "restaurant5",
        image_code : "5",
    },
    {
        code : "6",
        adresse : "Bizerte",    
        email : "restaurant6@gmail.com",
        enabled : true,
        name : "restaurant6",
        image_code : "6",
    },
    {
        code : "7",
        adresse : "Bizerte",    
        email : "restaurant7@gmail.com",
        enabled : true,
        name : "restaurant7",
        image_code : "7",
    },
    {
        code : "8",
        adresse : "Bizerte",    
        email : "restaurant8@gmail.com",
        enabled : true,
        name : "restaurant8",
        image_code : "8",
    },
    {
        code : "9",
        adresse : "Bizerte",    
        email : "restaurant9@gmail.com",
        enabled : true,
        name : "restaurant9",
        image_code : "9",
    },
    {
        code : "10",
        adresse : "Bizerte",    
        email : "restaurant10@gmail.com",
        enabled : true,
        name : "restaurant10",
        image_code : "10",
    },
    {
        code : "11",
        adresse : "Bizerte",    
        email : "restaurant11@gmail.com",
        enabled : true,
        name : "restaurant11",
        image_code : "11",
    },*/
]